services:
  backend-auth:
    build:
      context: .
      dockerfile: ./backend-auth/Dockerfile
    image: simike197/ds-proiect:backend-auth

  backend-user:
    build:
      context: .
      dockerfile: ./backend-user/Dockerfile
    image: simike197/ds-proiect:backend-user

  backend-device:
    build:
      context: .
      dockerfile: ./backend-devices/Dockerfile
    image: simike197/ds-proiect:backend-device

  backend-monitoring:
    build:
      context: .
      dockerfile: ./backend-monitoring/Dockerfile
    image: simike197/ds-proiect:backend-monitoring

  backend-messages:
    build:
      context: ./backend-messages
      dockerfile: Dockerfile
    image: simike197/ds-proiect:backend-messages

  device-simulator:
    build:
      context: .
      dockerfile: ./device-simulator/Dockerfile
    image: simike197/ds-proiect:device-simulator

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    image: simike197/ds-proiect:api-gateway

  load-balancer:
    build:
      context: .
      dockerfile: ./load-balancer/Dockerfile
    image: simike197/ds-proiect:load-balancer

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: simike197/ds-proiect:frontend

  swagger:
    build:
      context: .
      dockerfile: ./swagger/Dockerfile
    image: simike197/ds-proiect:swagger
