
authService:
  appName: "flask-auth"
  replicaCount: 1
  image: "registry.hub.docker.com/simike197/ds-proiect:backend-auth"
  postgresName: "postgres-auth"

userService:
  appName: "flask-user"
  replicaCount: 1
  image: "registry.hub.docker.com/simike197/ds-proiect:backend-user"
  postgresName: "postgres-user"

deviceService:
  appName: "flask-device"
  replicaCount: 1
  image: "registry.hub.docker.com/simike197/ds-proiect:backend-device"
  postgresName: "postgres-device"

monitoringService:
  appName: "flask-monitoring"
  replicaCount: 1
  image: "registry.hub.docker.com/simike197/ds-proiect:backend-monitoring"
  postgresName: "postgres-mon"

simulatorService:
  appName: "device-simulator"
  replicaCount: 1
  image: "registry.hub.docker.com/simike197/ds-proiect:device-simulator"


apiService:
  appName: "jwt-verifier"
  replicaCount: 1
  image: "registry.hub.docker.com/simike197/ds-proiect:api-gateway"

frontendService:
  appName: "frontend"
  replicaCount: 1
  image: "registry.hub.docker.com/simike197/ds-proiect:frontend"


swaggerService:
  appName: "swagger"
  replicaCount: 1
  image: "registry.hub.docker.com/simike197/ds-proiect:swagger"

rabbitmq:
  appName: "rabbitmq"
  replicaCount: 1

collectionRabbitmq:
  appName: "collection-rabbitmq"
  replicaCount: 1
  image: "rabbitmq:3-management"

secretKey: top123