
authService:
  appName: "flask-auth"
  replicaCount: 1
  image:
    repository: "registry.hub.docker.com/simike197/ds-proiect"
    tag: "backend-auth"
  postgresName: "postgres-auth"

userService:
  appName: "flask-user"
  replicaCount: 1
  image:
    repository: "registry.hub.docker.com/simike197/ds-proiect"
    tag: "backend-user"
  postgresName: "postgres-user"

deviceService:
  appName: "flask-device"
  replicaCount: 1
  image:
    repository: "registry.hub.docker.com/simike197/ds-proiect"
    tag: "backend-device"
  postgresName: "postgres-device"

monitoringService:
  appName: "flask-monitoring"
  replicaCount: 3
  image:
    repository: "registry.hub.docker.com/simike197/ds-proiect"
    tag: "backend-monitoring"
  postgresName: "postgres-mon"

simulatorService:
  appName: "device-simulator"
  replicaCount: 1
  image: "registry.hub.docker.com/simike197/ds-proiect:device-simulator"

messageService:
  appName: "flask-messages"
  replicaCount: 1
  image:
    repository: "registry.hub.docker.com/simike197/ds-proiect"
    tag: "backend-messages"
  storageSize: "1Gi"

loadBalancerService:
  appName: "load-balancer"
  replicaCount: 1
  image: "registry.hub.docker.com/simike197/ds-proiect:load-balancer"


apiService:
  appName: "jwt-verifier"
  replicaCount: 1
  image:
    repository: "registry.hub.docker.com/simike197/ds-proiect"
    tag: "api-gateway"

frontendService:
  appName: "frontend"
  replicaCount: 1
  image:
    repository: "registry.hub.docker.com/simike197/ds-proiect"
    tag: "frontend"


swaggerService:
  appName: "swagger"
  replicaCount: 1
  image:
    repository: "registry.hub.docker.com/simike197/ds-proiect"
    tag: "swagger"

rabbitmq:
  appName: "rabbitmq"
  replicaCount: 1

collectionRabbitmq:
  appName: "collection-rabbitmq"
  replicaCount: 1
  image: "rabbitmq:3-management"

secretKey: top123