apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-headers
  namespace: default
data:
  Authorization: $http_authorization


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress-protected
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://jwt-verifier-service.default.svc.cluster.local/verify"
    nginx.ingress.kubernetes.io/auth-proxy-set-headers: "default/auth-headers"
    nginx.ingress.kubernetes.io/websocket-services: "flask-messages-service"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
    - http:
        paths:
        - path: /users
          pathType: Prefix
          backend:
            service:
              name: flask-user-service
              port:
                number: 80
        - path: /edit-user
          pathType: Prefix
          backend:
            service:
              name: flask-user-service
              port:
                number: 80
        - path: /delete-user
          pathType: Prefix
          backend:
            service:
              name: flask-user-service
              port:
                number: 80
        - path: /user
          pathType: Prefix
          backend:
            service:
              name: flask-user-service
              port:
                number: 80
        - path: /admins
          pathType: Prefix
          backend:
            service:
              name: flask-user-service
              port:
                number: 80
        - path: /add-device
          pathType: Prefix
          backend:
            service:
              name: flask-device-service
              port:
                number: 80
        - path: /devices
          pathType: Prefix
          backend:
            service:
              name: flask-device-service
              port:
                number: 80
        - path: /delete-device
          pathType: Prefix
          backend:
            service:
              name: flask-device-service
              port:
                number: 80
        - path: /edit-device
          pathType: Prefix
          backend:
            service:
              name: flask-device-service
              port:
                number: 80
        - path: /consumptions
          pathType: Prefix
          backend:
            service:
              name: flask-monitoring-service
              port:
                number: 80
        - path: /chat
          pathType: Prefix
          backend:
            service:
              name: flask-messages-service
              port:
                number: 5005