apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ .Values.loadBalancerService.appName }}
  namespace: "default"
  labels:
    app: {{ .Values.loadBalancerService.appName }}
spec:
  replicas: {{ .Values.loadBalancerService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.loadBalancerService.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.loadBalancerService.appName }}
    spec:
      containers:
      - name: {{ .Values.loadBalancerService.appName }}
        image: {{ .Values.loadBalancerService.image }}
        imagePullPolicy: Always
        env:
          - name: "RABBIT_HOST"
            value: "collection-rabbitmq-service.default.svc.cluster.local"
          - name: "RABBIT_PORT"
            value: "5672"
          - name: "RABBIT_USER"
            value: "admin"
          - name: "RABBIT_PASS"
            value: "admin123"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ .Values.loadBalancerService.appName }}-service"
  namespace: "default"
  labels:
    app: {{ .Values.loadBalancerService.appName }}
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5001
  selector:
    app: {{ .Values.loadBalancerService.appName }}
  type: "ClusterIP"